---
- name: Required packages are installed
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - python-psycopg2
  - node-less  # Required for in-request django-compressor compression.
  - procmail  # To get the lockfile command which we use in our playbook.

- name: Project user is present
  user:
    name: "{{ gunicorn_django_project_name }}"

- name: Home directory is present
  file:
    name: "/home/{{ gunicorn_django_project_name }}"
    state: directory
    owner: "{{ gunicorn_django_project_name }}"
    group: "{{ gunicorn_django_project_name }}"

- name: Gunicorn .service file is in place
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.{{ gunicorn_django_project_name }}@.service
  notify: Reload systemd units

- include: celery.yml
  when:  deploy_celery
